### ISSUE TITLE
Ask questions

### ISSUE THREAD

**Issue by cyk2018** [Leporacanthicus/lacsap#1]
Hello!

I am writing a program to generate the LLVM IR use APIs. When I want to create the IR of  array, I use the function "AllocaInst " which means "AllocaInst(Type *Ty, unsigned AddrSpace, Value *ArraySize, const Twine &Name, BasicBlock *InsertAtEnd);" in IR/Instruction.h.
My question is how can I create the ArraySize whose type is Value*. What I have now is how many dimensions it is and the lengths of each dimension.
Looking forward for your reply！

**Comment by Leporacanthicus** [comment]
In my compiler, I just take all the sizes (which are ranges, since Pascal allows an array to be declared as `array [12..24] of integer;` for example, giving 13 elements).

I think, in principle, you could also create multiple layers of arrays, so that `Ty` is a type declared as an array, with another array inside it.

See https://github.com/Leporacanthicus/lacsap/blob/master/types.cpp#L310 for creating the type and calculating the number of elements. My code uses that LLVMType to allocate a single object with alloca, but you could just use the base-type and calculate the total number of elements as a flat array.

Using the array elements is done here https://github.com/Leporacanthicus/lacsap/blob/master/expr.cpp#L488, and again, I'm just using a flat array and calculating the index as one single index, using GEP instruction.
